<?php
/**
 * Created by PhpStorm.
 * User: lusc
 * Date: 2016/5/18
 * Time: 12:13
 */

namespace api\modules\v01;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'api\modules\v01\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
