<?php
/**
 * storage
 * User: lushuncheng<admin@lushuncheng.com>
 * Date: 2017/3/9
 * Time: 17:23
 * @link https://github.com/lscgzwd
 * @copyright Copyright (c) 2017 Lu Shun Cheng (https://github.com/lscgzwd)
 * @licence http://www.apache.org/licenses/LICENSE-2.0
 * @author Lu Shun Cheng (lscgzwd@gmail.com)
 */

namespace storage\modules\v1\controllers;

use yiiswoole\web\Controller;

class BaseController extends Controller
{
    protected $requestBegin;
    /**
     * @param $id
     * @param array $params
     * @return mixed
     */
    public function runAction($id, $params = [])
    {
        $this->requestBegin = microtime(true) * 1000; // record request begin time
        // record request
        $this->logRequest($id);

        $result = parent::runAction($id, $params); // TODO: Change the autogenerated stub
        // record the response
        $this->logResponse($result, $id);
        return $result;
    }
    /**
     * log the request
     */
    public function logRequest($actionId = '')
    {
        \Start::$instance->addLog('controller_request_begin', 'info', [
            'post'   => \Yii::$app->getRequest()->post(),
            'get'    => \Yii::$app->getRequest()->get(),
            'server' => $_SERVER,
            'header' => \Yii::$app->getRequest()->getHeaders(),
        ], $this->id . '-' . (empty($actionId) ? 'default' : $actionId));
    }

    /**
     * log the output
     * @param $content
     */
    public function logResponse($content, $actionId = '')
    {
        $elapsed = microtime(true) * 1000 - $this->requestBegin;
        \Start::$instance->addLog('controller_request_end', 'info', [
            'content' => $content,
            'elapsed' => floatval($elapsed), // time the request cost
        ], $this->id . '-' . (empty($actionId) ? 'default' : $actionId));

    }
}
