<?php

namespace api\modules\oss;

class Module extends \yii\base\Module
{
    public $controllerNamespace = 'api\modules\oss\controllers';
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}
