<?php
namespace common\controllers;

use common\constants\ModelConst;
use Yii;

/**
 * Api base controller, implement common sign check
 * Class ApiBaseController
 * @package common\controllers
 */
class ApiBaseController extends BaseController
{
    protected $needCheckSign     = true; // mark for need check sign
    protected $signExcludeFields = ['sign']; // fields in request must been filter when check sign
    protected $safeDateDiff      = 30; // security time to api request limit between client and server, unit seconds

    /**
     * execute before the action method
     */
    public function beforeAction($action)
    {
        if ($this->needCheckSign == true && $this->checkSign() === false) {
            $response       = Yii::$app->getResponse();
            $result         = ModelConst::getResult(ModelConst::SIGN_ERROR);
            $response->data = $result;
            $this->logResponse($result);
            \Yii::$app->getResponse()->format = $this->outContentType;
            return false;

        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 验证签名
     * 把客户端上传的参数，去除不参加验签的字段后，升序排列
     * 然后组成http url query 字符串
     * 在字符串后面拼接&appkey=key
     * 取MD5
     * @return boolean
     */
    public function checkSign()
    {
        $data = Yii::$app->getRequest()->getBodyParams();
        if (!isset($data['ts'])) {
            return false;
        }
        if ($_SERVER['REQUEST_TIME'] - $data['ts'] > $this->safeDateDiff) {
            return false;
        }
        $_clientSign = $data['sign'];
        foreach ($this->signExcludeFields as $_field) {
            unset($data[$_field]);
        }
        ksort($data);
        $str = http_build_query($data);
        $str .= '&appkey=' . Yii::$app->params['apps'][$data['appid']];

        $serverSign = md5($str);
        Yii::info("sign: str:" . $str . ", serversign:" . $serverSign . ',clentsign:' . $_clientSign);
        return $serverSign == $_clientSign;
    }
}
