<?php
namespace common\controllers;

use Yii;

/**
 * Api基类，实现统一的验签
 * Class ApiBaseController
 * @package common\controllers
 */
class ApiBaseController extends BaseController
{
    protected $needCheckSign     = true; // 是否需要验签
    protected $signExcludeFields = ['sign']; // 验签需要过滤的字段
    protected $safeDateDiff      = 30; // 接口请求时间误差30秒

    /**
     * 控制器初使化方法
     */
    public function beforeAction($action)
    {
        if ($this->needCheckSign == true && $this->checkSign() === false) {
            $response = Yii::$app->getResponse();
            $result   = [
                'error' => [
                    'returnCode'        => 401,
                    'returnMessage'     => '签名错误',
                    'returnUserMessage' => '签名错误',
                ],
                'data'  => null,
            ];
            $response->data = $result;
            $this->logResponse($result);
            \Yii::$app->getResponse()->format = $this->outContentType;
            return false;

        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 验证签名
     * 把客户端上传的参数，去除不参加验签的字段后，升序排列
     * 然后组成http url query 字符串
     * 在字符串后面拼接&appkey=key
     * 取MD5
     * @return boolean
     */
    public function checkSign()
    {
        $data = Yii::$app->getRequest()->getBodyParams();
        if (!isset($data['ts'])) {
            return false;
        }
        if ($_SERVER['REQUEST_TIME'] - $data['ts'] > $this->safeDateDiff) {
            return false;
        }
        $_clientSign = $data['sign'];
        foreach ($this->signExcludeFields as $_field) {
            unset($data[$_field]);
        }
        ksort($data);
        $str = http_build_query($data);
        $str .= '&appkey=' . Yii::$app->params['apps'][$data['appid']];

        $serverSign = md5($str);
        Yii::info("sign: str:" . $str . ", serversign:" . $serverSign . ',clentsign:' . $_clientSign);
        return $serverSign == $_clientSign;
    }
}
