<?php
/**
 * app项目入口基类
 * 实现登录态验证
 * User: lusc
 * Date: 2016/5/5
 * Time: 22:45
 */

namespace common\controllers;

class AppBaseController extends BaseController
{
    public $userId       = null;
    public $userInfo     = null;
    public $needLogin    = true;
    public $sessionToken = null;

    public function beforeAction($action)
    {
        if ($this->needLogin && $this->validSessionToken() === false) {
            $response = \Yii::$app->getResponse();
            $result   = [
                'error' => [
                    'returnCode'        => 5001,
                    'returnMessage'     => '登录失效',
                    'returnUserMessage' => '登录失效',
                ],
                'data'  => null,
            ];
            $response->data = $result;
            $this->logResponse($result);
            \Yii::$app->end(0, $response);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function validSessionToken()
    {
        return true;
    }
}
