<?php
/**
 * Trait for BaseController
 * User: lusc
 * Date: 2016/9/6
 * Time: 14:16
 */

namespace common\controllers;

use common\helpers\Trace;
use swoole\SwooleServer;

trait BaseControllerTrait
{

    /**
     * execute before action method
     * @param \yii\base\Action $action
     */
    public function beforeAction($action)
    {
        $this->requestBegin               = microtime(true) * 1000;
        \Yii::$app->getResponse()->format = $this->outContentType;
        $this->logRequest();
        return parent::beforeAction($action);
    }

    /**
     * execute after action method
     * rewrite the response to special format
     * @param \yii\base\Action $action
     * @param mixed $result
     * @return mixed
     */
    public function afterAction($action, $result)
    {
        \Yii::$app->getResponse()->format = $this->outContentType;
        $traceId                          = '';
        if (defined('IN_SWOOLE') && IN_SWOOLE) {
            $traceId = SwooleServer::$swooleApp->logTraceId;
        } else {
            defined('YII_TRACK_ID') or define('YII_TRACK_ID', md5(microtime(true) . rand(0, 10000) . implode('', $_SERVER)));
            $traceId = YII_TRACK_ID;
        }
        if (is_array($result) && isset($result['errno'])) {
            $newResult = [
                'error'   => [
                    'returnCode'        => $result['errno'] == 200 ? 0 : $result['errno'],
                    'returnMessage'     => $result['msg'],
                    'returnUserMessage' => $result['msg'],
                ],
                'traceId' => $traceId,
                'data'    => isset($result['data']) ? $result['data'] : null,
            ];
            $result = $newResult;
            unset($newResult);
        }
        $this->logResponse($result);
        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }

    /**
     * log the request
     */
    public function logRequest()
    {
        Trace::addLog('controller_request_begin', [
            'post'   => \Yii::$app->getRequest()->post(),
            'get'    => \Yii::$app->getRequest()->get(),
            'server' => $_SERVER,
            'header' => \Yii::$app->getRequest()->getHeaders(),
        ], $this->id . '_' . $this->action->id);
    }

    /**
     * log the output
     * @param $content
     */
    public function logResponse($content)
    {
        $elapsed = microtime(true) * 1000 - $this->requestBegin;
        Trace::addLog('controller_request_end', [
            'post'    => \Yii::$app->getRequest()->post(),
            'get'     => \Yii::$app->getRequest()->get(),
            'server'  => $_SERVER,
            'header'  => \Yii::$app->getRequest()->getHeaders(),
            'content' => $content,
            'elapsed' => floatval($elapsed), // time the request cost
        ], $this->id . '_' . $this->action->id);
    }
}
