<?php
/**
 * Created by PhpStorm.
 * User: lusc
 * Date: 2017/8/9
 * Time: 23:05
 */

namespace yiiswoole;

class Module extends \yii\base\Module
{
    protected static $controllerInstances = [];

    /**
     * @param string $route
     * @return array|bool
     */
    public function createController($route)
    {
        if ($route === '') {
            $route = $this->defaultRoute;
        }
        if (!isset(static::$controllerInstances[$route])) {
            $controller = parent::createController($route); // TODO: Change the autogenerated stub
            if (false !== $controller) {
                static::$controllerInstances[$route] = $controller;
            }
        }
        if (isset(static::$controllerInstances[$route])) {
            return [
                clone static::$controllerInstances[$route][0],
                static::$controllerInstances[$route][1],
            ];
        } else {
            return false;
        }
    }
}
